# Generated by Django 5.1.1 on 2024-09-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_venue_city_alter_venue_email_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='MyClubUser',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
