# Generated by Django 5.1.1 on 2024-10-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_venue_venue_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo_event',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
